[build]
  command = "pip install -r requirements.txt"
  publish = "static"
  functions = "netlify/functions"

[dev]
  framework = "python"
  command = "python app.py"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  node_bundler = "esbuild"
