services:
  - type: web
    name: examination-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: humam2003
      - key: DATABASE_URL
        fromDatabase:
          name: examination-db
          property: connectionString
      - key: FLASK_DEBUG
        value: "0"

databases:
  - name: examination-db
    plan: free
    ipAllowList: []